#!/bin/bash
read -r -p "Please enter the name of the script: " script
read -r -p "Input your full name: " fname
read -r -p "The description of the script: " des

echo "#!/bin/bash" > /home/ofdove/code/bashUtils/${script}
echo 
echo "##################################################" >> /home/ofdove/code/bashUtils/${script}
echo 
echo "#Author: " $fname >> /home/ofdove/code/bashUtils/${script}
echo 
echo "#Date: " $(date) >> /home/ofdove/code/bashUtils/${script}
echo 
echo "#Description: " $des >> /home/ofdove/code/bashUtils/${script}
echo
echo "##################################################" >> /home/ofdove/code/bashUtils/${script}
echo 
chmod a+x /home/ofdove/code/bashUtils/${script}
helix /home/ofdove/code/bashUtils/${script}
